### PR TITLE
Added NodeTooltipAttribute, to give tooltips to nodes header label.

### PR DESCRIPTION
**Pull request by nostek**
Also fixed tooltip on ports where its drawn with a label only.

### CODE REVIEW

**Comment by nostek** [comment]
On labels Unitys ToolTipAttribute is used.
But its only for fields and can not be used on classes, so therefor I added NodeTooltipAttribute.

**Comment by Siccity** [comment]
This is too much extra code to maintain for something that can be done as a one-line OnHeaderGUI override

**Comment by nostek** [comment]
The first commit fixes expected unity inspector behaviour, tooltips works on unconnected ports but not connected ports.

And how would you solve it with a override? so I can add it to my project instead

**Comment by Siccity** [comment]
Ah i didn't see you had two new features in here. Can you separate them?

The override is basically just what you implemented, but manually:
```cs
public override void OnHeaderGUI() {
    GUILayout.Label(new GUIContent(target.name, "This is my node"), NodeEditorResources.styles.nodeHeader, GUILayout.Height(30));
}
```

**Comment by nostek** [comment]
Can do!

But that means adding a node editor for every node I want to have a tooltip on, but sure it could be abstracted.

**Comment by Siccity** [comment]
you just have to make a base node and an editor for that, then you can control it all from one place. You can even implement your attribute in that base node and have it work without modifying the core :)

**Comment by nostek** [comment]
True! Will do that.

Updated the branch and removed NodeTooltipAttribute

**Pull request closed without merging**
