### PR TITLE
Allow graphs to repaint on update

### PR DESCRIPTION
**Pull request by jlreymendez**

### CODE REVIEW

**Comment by jlreymendez** [comment]
Thanks for reviewing this. I don't think your proposed solution has the same result as I expect. Since OnGUI isn't executed necessarily during Update. 

Since NodeGraphEditor is a subclass of ScriptableObject and doesn't have an Update function the only possible solution I found was doing it in the NodeEditorWindow. I will think this through a bit more, since I understand your point of keeping editor code separate from logic code.

**Comment by Siccity** [comment]
Calling Repaint does not directly repaint the GUI. Instead, it will flag the EditorWindow to be repainted at next GUI cycle. I don't think calling Repaint from Update or OnGUI makes any difference. Can you present a usecase where doing it in OnGUI isn't adequate?

**Comment by jlreymendez** [comment]
@Siccity I have tested your solution again on a cleaner project and you are completely right your solution works as expected. Thanks for your time! 
Maybe it is a good idea to add this as a comment in the documentation. What do you think?

**Comment by Siccity** [comment]
Added in https://github.com/Siccity/xNode/wiki/Graph%20Editors :)

**Pull request closed without merging**
