### PR TITLE
Added TypeConstraint to check inheritance but inverted.

### PR DESCRIPTION
**Pull request by nostek**
TypeConstraint.Inherited checks if A is assignable from B.
TypeConstraint.InheritedInverse checks if B is assignable from A.

### CODE REVIEW

**Comment by Siccity** [comment]
Try this. Now that output is flipped you don't need a InheritedInverse to match an Inherited
You can simply do

```cs
[Input(typeConstraint = TypeConstraint.Inherited)] public Object inObj;
````
```cs
[Input(typeConstraint = TypeConstraint.Inherited)] public Object inObj;
````

**Comment by Siccity** [comment]
Try this. Now that output is flipped you don't need a InheritedInverse to match an Inherited
```cs
[Input(typeConstraint = TypeConstraint.Inherited)] public Object inObj;
````
Now connects to
```cs
[Output(typeConstraint = TypeConstraint.Inherited)] public ScriptableObject outSO;
````

**Comment by nostek** [comment]
Yes! Works as expected for me.

Tested with:
`
[Output(typeConstraint = TypeConstraint.InheritedInverse)] ScriptableObject SO -> [Input(typeConstraint = TypeConstraint.InheritedInverse)] ChildScriptableObject CSO
`

**Comment by LumosX** [comment]
@Siccity: The way this is implemented currently doesn't really make any sense. This makes output connections _inverted_ in comparison with input connections, which is at the very least unintuitive.

In the example given in Nostek's post above, the Output node's type constraint being `InheritedInverse` should accept `ScriptableObject`s and _above_, not types _inheriting from_ ScriptableObject. In fact, Nostek's base commit is the correct and intuitive way to implement this feature.

Consider this: we have the following inheritance relationships: `Object > ScriptableObject > ChildScriptableObject` where `A > B` ≡ `A > ... > B | class B : A { [...] }` (i.e. `B.isAssignableFrom(A)`)
Thus, we can posit that:
* A connection of type `Inherited` at node of type `T` should accept any nodes of type `U` where `T > U`;
* A connetciton of type `InheritedInverse` at node of type `T` should accept any nodes of type `S` where `S > T`.

This keeps the rules consistent and sensible. If you wish to model an `A > B` relationship, your output is set to `Inherited` and your input is set to `InheritedInverse` to fulfil it. Modelling a `B > A` relationship mandates reversing those.

It doesn't make any sense for both nodes to be set to the same type constraint yet have mirrored functionality. In fact, I almost submitted this as a bug report before deciding to check out this pull request in detail.

**Comment by Siccity** [comment]
It makes sense if you read the comments.
```cs
// Allow connections where input value type is assignable from output value type (eg. ScriptableObject --> Object)
Inherited,
// Allow connections where output value type is assignable from input value type (eg. Object --> ScriptableObject)
InheritedInverse,
```
The options are designed to match the direction of connections.
In most cases, people want to use `Inherited` to pass some class from an output to an input.
In the off case that you want to pass data the other way, you can use `InheritedInverse`. 
This is much simpler to explain and easier to wrap your head around. 
If it had been any other type of framework where direction wasn't key, i'd agree with you.

**Comment by LumosX** [comment]
Fair enough, there's an argument for taking direction into account. That said, I disagree that this is clearer or simpler; my first instinct being to look for bugs proves that (though YMMV, obviously 😃). I've spoken my piece in the previous post, and I guess we can agree to disagree. After all, your job is to call the shots and mine is to report things that look odd.

**Pull request merged**
