### PR TITLE
default name for all nodes

### PR DESCRIPTION
**Pull request by KoalaHao**
Nodes default to their class name

### CODE REVIEW

**Comment by nostek** [comment]
There is two different ways right now a node name is determined, this should probably be merged in to one utility function.

https://github.com/Siccity/xNode/blob/0553dc889487c178ac4c7795f650b37174ceffc9/Scripts/Editor/NodeGraphEditor.cs#L79

https://github.com/Siccity/xNode/blob/0553dc889487c178ac4c7795f650b37174ceffc9/Scripts/Editor/RenamePopup.cs#L51

**Comment by nostek** [comment]
@KoalaHao what would call this Reset function ?

**Comment by KoalaHao** [comment]
Upon creating a ScriptableObject, Reset is called, this will give it a default node name

**Comment by Siccity** [comment]
Is this still relevant?
Seems like node names were fixed in #161
And it seems like you also have the changes from #162 in this branch

**Pull request closed without merging**
