### PR TITLE
Graph Variables

### PR DESCRIPTION
**Pull request by Orcolom**
Added graph variables.

variable type selectable via dropdown (popup). Will show some basics (float, int, Vector3, string, ...) and all types known by the graph

### CODE REVIEW

**Comment by Siccity** [comment]
I looked at your request. It is a good implementation but i fail to see why this is necessary to include in the base xNode. It seems more suited as an an optional extension.

**Comment by Orcolom** [comment]
In general variables are handy in any node based workflow

using some projects as example:
dialogue -> known information trigger, username to put in text, ...
graphmesh -> dynamic material, ...

other usecases:
quests -> collected item count, other quests, ...
terrain -> input height map, ...

**Comment by Siccity** [comment]
All of those are examples that would have been better off with variables stored outside the scope of the graph. 

dialogue -> store user data in a separate PlayerData container shared by all of your game logic, or component so two NPC's with different names can use the same graph.
graphmesh -> multiple components referring to the same graph needs different input variables.
quests -> item count and quest info really shouldn't be stored in the graph, also better suited as a separate container.
terrain -> input heightmap could just as well be plugged in to the first node.

Again, i think this is too use-case and architecture specific to be included in the main branch. I am considering the possibility of an xNode Extended branch though, with features such as this.

**Comment by Orcolom** [comment]
I think it works in both cases, but I see your point. 
The code will always be here if anybody needs/wants it

**Pull request closed without merging**
