### PR TITLE
NodeEditorReflection: Catch ReflectionTypeLoadException

### PR DESCRIPTION
**Pull request by vvoland**
Can happen if some dll can not be loaded for some reason.

### CODE REVIEW

**Comment by vvoland** [comment]
Technically they are unnecessary. However if at some point this code got extracted to file that is not in an Editor folder, having them around would indicate clearly that the try-catch is intended to be in Editor-only context

Although given the strong separation of editor code that scenario is not very likely so we can remove them if you think they are redundant.

**Comment by Siccity** [comment]
Perhaps we should add a Debug.Log or something to notify the user that something went wrong? I don't know what triggers this exception so i can't tell if it's necessary

**Comment by vvoland** [comment]
In the situation I encountered this error Unity was already issuing an error:


So it's probably not necessary to issue another warning

**Comment by Siccity** [comment]
Yeah, but will that error still appear with the try/catch fix?

**Pull request merged**
