### PR TITLE
Added node groups

### PR DESCRIPTION
**Pull request by Jeroenimoo0**
### Features
- Create, Rename, Delete, Copy comments
- Drag sides to resize the comment
- Shift click to (un)select all nodes inside the comment

### Screenshots
ezgif-4-7ecb70b2eae9
ezgif-4-7fe83cdf6bc9

### Implementation
Some details on certain implementation decisions:

**ScriptableObject**
Comments are ScriptableObjects. While my initial idea was to not do this as it is not required like it is for nodes. However to integrate well with nodes (selecting etc) I ended up turning them into ScriptableObjects anyways.

**Editor code**
Node rendering happens inside the NodeEditor, however since comments do not require as much rendering I put the rendering code inside NodeEditorGUI.

**Zooming**
The comments just like nodes required zooming. By default however the Begin- & EndZoomed methods did not support being used multiple times. After a lot of debuging I managed to get them to work sequentially using the methods described in this post: http://martinecker.com/martincodes/unity-editor-window-zooming/

**Selection UX**
My expectations on how comment selection should work are quite different from they way selecting works with nodes. Clicking inside the comment should select it, but right clicking to create nodes etc should still work. It's hard to explain the current setup so I would say give it a try and let me know if you feel this is the right experience.

### Problems
Some current problems with the current implementation:

**Runtime comment**
Comments are currently serialized and are also included at runtime. This might not be the desired behaviour. Especially since it's not implemented in the runtime implementation of xNode.

**Grid snapping**
Comments do currently not support grid snapping when scaling. When moving there are also some minor placement artifacts due to grid snapping. I feel however this is not a major problem and could be fixed in the future.

### Feedback
If you have any questions, feedback or implementation issues let me know. I looked at the diff for any code conventions, at work I use different conventions so I might have missed something. Overall I think comments could be a good general addition to the plugin so I hope you like this.

### CODE REVIEW

**Comment by Jeroenimoo0** [comment]
Another implementation node:

Currently there is a lot of similar/duplicate code as nodes & comments do have a lot of overlapping logic. Giving them a common base class however I would think might be a bit too intrusive. They should still be stored separately imo as one is logic and the other is just for the editor. Doing this to reduce code is still an option however and I could still investigate this if you would like that.

**Comment by Siccity** [comment]
Great implementation!

If we are to add this to the main branch, it should be as part of a long discussed featureset https://github.com/Siccity/xNode/issues/16
Eventually it would be able to collapse all encompassed nodes and display appropriate in/output ports.

That being said, i think it should be called NodeGroup instead of Comment to be more intuitive in future API such as `List<Node> mathNodes = graph.GetGroup("Math logic).nodes`

**Comment by Siccity** [comment]
I'm actually considering how NodeGroup could be used in runtime as a way to get certain nodes.

Keeping it out of runtime could be a tough task, so at least try to keep the data used to a minimum.

**Comment by Jeroenimoo0** [comment]
Okay I refactored everything 'comment' to 'group' & made the groups use the (Scriptable)Object.name instead of having an extra field.

I also found a bug with the new zooming that caused nodes to be rendered offset when the window was being dragged around so I fixed it.

To make groups inside groups work better I also added the 'Move To Top' option nodes have to groups. And updated shift selecting a group to also select groups inside.

**Comment by Joshua-Swin** [comment]
Has this been merged into master? It would be a really nice feature to have.

**Comment by paulbettner** [comment]
What's the status on this PR @Siccity ? Would be great to have on master...

**Comment by Siccity** [comment]
An external plugin has been made that lets you add node groups! Find it here https://github.com/Siccity/xNodeGroups

**Pull request closed without merging**
