### PR TITLE
Fix wrong override message.

### PR DESCRIPTION
**Pull request by marcosecchi**
Fixing a minor error message.

### CODE REVIEW

**Comment by nostek** [comment]
I vote to remove the Debug.Log message all together, very annoying for us that don't use it.

**Comment by Siccity** [comment]
> 
> 
> I vote to remove the Debug.Log message all together, very annoying for us that don't use it.

Can you explain your situation? It should only appear once when you drop an object on the xNode window without having it overridden.

**Comment by nostek** [comment]
> Can you explain your situation? It should only appear once when you drop an object on the xNode window without having it overridden.

It happens when I drag a ScriptableObject asset from the Project View to a [SerializeField] in the node.

**Comment by Siccity** [comment]
> It happens when I drag a ScriptableObject asset from the Project View to a [SerializeField] in the node.

Ah, well perhaps we can fix that without removing the message entirely.
I think the message does its job in exposing this functionality to people who might need it.

**Pull request merged**
