### PR TITLE
Added support for copy paste

### PR DESCRIPTION
**Pull request by nostek**
Added support for copy paste in menu and ctrl+c / ctrl+v / cmd+c / cmd+v.

### CODE REVIEW

**Comment by nostek** [comment]
Didn't want to change existing code, but I can change that asap.

**Comment by Siccity** [comment]
I think it would be better. Less code to maintain if we ever need to fix something in it.

**Comment by Siccity** [comment]
I had some time available so i gave it a shot myself. It seems to work fine on my end. Could you test if it works for you and report back here? :)

**Comment by nostek** [comment]
Works fine for me!
Did a final change so both function uses the same linq-select, yours looked nicer, so copied it.

**Pull request merged**
