### PR TITLE
Add Unity Package Manager support

### PR DESCRIPTION
**Pull request by gpoole**
Thanks for your work creating this very useful tool! This change adds Assembly Definitions and `package.json` to support installing xNode through the Unity Package Manager. As I've added in the readme, the package will be able to be installed by adding the following to `manifest.json`:

```json
"com.github.siccity.xnode": "git+https://github.com/siccity/xNode.git"
```

You can test this change works by installing from my branch:

```json
"com.github.siccity.xnode": "git+https://github.com/gpoole/xNode.git#upm-support"
```

I've also added Assembly Definitions to make this usable with projects that need those. As mentioned in [the Unity docs on Assembly Definitions](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) (in the section _Backwards compatibility and implicit dependencies_), this should still be backwards compatible with projects that don't use Assembly Definitions.

To make this work I had to un-ignore some .meta files for the `.md` files in the root directory. If these meta files are not included, the package will fail to install with errors like "Read only asset README.md has no meta file.". Unfortunately I can't work around that because [.npmignore won't allow me to exclude README.md or LICENSE.md](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package). Hopefully that isn't a major problem!

I tested and confirmed everything works correctly with Unity 2019.1.8f1.

### CODE REVIEW

**Comment by Siccity** [comment]
Been wanting to add this for a while. Thanks a lot for setting it all up!

**Comment by Siccity** [comment]
I got the following error on import
```An error occurred while resolving packages:
  Project has invalid dependencies:
    com.github.siccity.xnode: Version is invalid.  Expected a pattern like 'x.x.x[-prerelease]', got 'git+https://github.com/siccity/xNode.git' instead.

A re-import of the project may be required to fix the issue or a manual modification of E:/Unity/MyProject/Packages/manifest.json file.```
Do you know why?

**Comment by Siccity** [comment]
Figured if i used a newer version of unity (was on 2018.2) and removed `git+` from the url, it would complain about missing git on my machine instead, which is okay i guess.

* Why did you add `git+`?
* And at what point did the UPM start supporting git packages?
  * According to [this post](https://forum.unity.com/threads/git-support-on-package-manager.573673/) it's 2018.3.0b7. Confirm?

**Comment by gpoole** [comment]
@Siccity sorry, my mistake, 2018.3.0b7 would be the minimum supported version yes. I've just tried installing on both 2018.2 and 2018.3 and it does only work from 2018.3 up.

I used `git+` since [that's what NPM says it needs](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies), but it seems like plain HTTPS is fine here. I thought it didn't work when I was setting it up, but I just tried it and it works fine for me too. It shouldn't matter either way though, I think the original problem was that 2018.2 doesn't support Git dependencies at all.

You will need Git installed and in your system path to use it, yes. I've opened a new PR (#167) with some extra docs on that just in case.

**Pull request merged**
